### ISSUE TITLE
How can I use gassetic with compass (sass)?

### ISSUE THREAD

**Issue by robertfausk** [crossborne/gassetic#42]
How will I be able to use gassetic with compass?

By importing compass specific files I get 
_Error: error frontend_10.scss (Line 3: File to import not found or unreadable: compass/reset._

Below my config.

```
#gassetic.yml
requires:
    sass: gulp-ruby-sass
mimetypes:
    # This section contains the formatters for the css files
    css:
        dev:
            outputFolder: web/css/compiled  # The output folder for your saving your compiled files
            webPath:      /css/compiled     # The web path for the compiled files
            # Run these tasks on your compiled files
            tasks:
                - { name: sass }
            htmlTag: '<link rel="stylesheet" type="text/css" href="{{ asset("%path%") }}">' # custom html tag

        # This is the list of source files to apply the above settings
        files:
            frontend: # This is the output filename
                - src/Acme/FrontendBundle/Resources/public/css/*.scss

# This is the list of files/paths to search and find the replacement tags to insert the
# generated <script> or stylesheet tags
replacementPaths:
    - src/Acme/FrontendBundle/Resources/views/layout.html.twig

default:
    - css
```
```
# src/Acme/FrontendBundle/Resources/public/css/frontend.scss

@import "compass/reset";    # this causes build to fail
@import "grid-settings";
...
```

I also tried _gulp-compass_ as lib but with no luck in getting gassetic running.
Could you please give me a hint or provide an example or update doc?
